### ISSUE TITLE
use type=module

### ISSUE THREAD

**Issue by LarchLiu** [antfu/unplugin-starter#16]
### Clear and concise description of the problem

Just like PR of [unplugin-auto-import #243](https://github.com/antfu/unplugin-auto-import/pull/243), should we use it as that in this template? 

### Suggested solution

We can merge it if necessary.
And some other `unplugin` may be have the same issues, such as unplugin-vue-components.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
For sure, pr welcome
