### ISSUE TITLE
Writing a Nuxt module using an Unplugin foundation

### ISSUE THREAD

**Issue by tropicalraisel** [antfu/unplugin-starter#4]
In https://github.com/unjs/unplugin/issues/23, I realized the README reference was to this project, not Unplugin. Time for ☕ !

Insert that question here.

**Comment by antfu** [comment]
I don't really understand what you are expected tho. The nuxt support is here: https://github.com/antfu/unplugin-starter/blob/main/src/nuxt.ts

**Comment by TropicalRaisel** [comment]
Ok I'll test things out and report back if any issues are encountered. If everything's good to go I'll close this issue

**Comment by TropicalRaisel** [comment]
I'm using the same config from earlier:
```javascript
export default {
  generate: {
    dir: 'dist/nuxt',
  },
  modules: [['unplugin-skypin/nuxt', { /* options */ }]],
}
```
And get a `Error: Cannot find module 'unplugin-skypin/nuxt'` `Nuxt Fatal Error`.

**Comment by tropicalraisel** [comment]
I'm guessing users are supposed to make a module similar to the following in `nuxt.ts`: https://github.com/nuxt-community/ngrok-module/blob/main/src/module.ts

Also, are users supposed to use the `nuxt-vite` module alongside an Unplugin? The `vite:extend` hook is only available alongside it: https://vite.nuxtjs.org/advanced/modules/

**Comment by tropicalraisel** [comment]
It's a bit involved but I got it at least building!

https://github.com/tropicalraisel/unplugin-skypin/commit/89fe81b86dd587b8dd02436165b77375a4a7f316
